name: Auto Update AI News

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 8:30 AM IST (3 AM UTC)
  workflow_dispatch:      # Allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install feedparser
        run: pip install feedparser

      - name: Run update script
        run: python scripts/update_news.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/news.json
          git commit -m "🤖 Auto-update AI news" || echo "No changes to commit"
          git push
